baseurl: "https://recurrentanalytics.netlify.app/"
languageCode: "en-us"
title: "re:current_analytics"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; [Timm Walker](https://recurrentanalytics.com) 2021 --  | [Github](https://github.com/recurrentanalytics) | [Twitter](https://twitter.com/timm_walker)"

markup:
  goldmark:
    renderer:
      unsafe: true
